import React from 'react'
import './square.css'

class Square extends React.Component {
	constructor(props) {
		super(props)
		this.position = this.props.position;																															// a 2d array like [0,0] generated by the Board components render loop 
		this.handleClick = this.handleClick.bind(this)
		this.drop = this.drop.bind(this)
		this.fontSize = '2rem'
	}

	handleClick(e) {
		this.props.handleClick(this.props.position[0],this.props.position[1])													// this passes the Game component's playMove method the value of the caller which mutates this.props.playerBoard
		if (this.props.board.playerBoard[this.position[0]][this.position[1]] === 'B') {										// Checks the board to see if it was a bomb
			alert('BOOM!!!')
		}
	}

	allowDrop(e) {
		e.preventDefault()
	}

	drop(e) {
		this.props.handleDrop(e,this.position)
	}

						// below we render a button with a value equal to its index that will be recalled on click. Button will display content at the index of playerBoard
	render() {
		if(this.props.board.playerBoard[0].length > 17) {this.fontSize = '1rem'} else {this.fontSize = '2rem'}
		this.style = {border: (1/this.props.board.playerBoard.length)*9+'vw outset', fontSize: this.fontSize};
		let content = this.props.board.playerBoard[this.position[0]][this.position[1]]
		if(content !== ' ') {
			this.style = {border: '1px solid darkgray',	overflow: 'hidden', fontSize: this.fontSize}
		}

		return (
		  <button className='square' 
		  	onClick={this.handleClick} 
				onDragOver={this.allowDrop}
				onDrop={this.drop}
				style={this.style}
			>
	  		{content}
	  		{this.props.children}
		  </button>
		)
	}
}

export default Square